name: Lint, Test, and Coverage Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.9"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint -r requirements.txt

      - name: Pylint Analysis
        run: pylint $(git ls-files '*.py')

      - name: Run Unit Tests and Coverage
        run: |
          coverage run -m unittest discover -s tests -p '*_test.py'
          coverage report --fail-under=80
          coverage report | grep -E "^\s+[0-7][0-9]%"
